name: CD

# Only trigger, when the CI workflow succeeded

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  push_container:
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: 'Login to ghcr'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build image
      run: |
        docker build . --tag ghcr.io/${{github.repository}}:${{github.sha}}
        docker push ghcr.io/${{github.repository}}:${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    needs: [push_container]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            docker-compose -d up