name: CI
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/checkout@v3
      uses: actions/setup-go@v3
      with:
        go-version: '1.15.x'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v3
