name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.x'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: |
        go build -v ./...
        go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint
      uses: golangci/golangci-lint-action@v3