name: CI
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17.x'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test with the Go CLI
      run: go test -v ./...
  
  lint-except-go: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint
      uses: github/super-linter@v4
      env:
        #best linting practices
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JSON: false
        VALIDATE_YAML: false
        VALIDATE_GO: false
        VALIDATE_JSCPD: false
        VALIDATE_CSS: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        